version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080